name: Publish API documentation (release)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-doc-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make scripts executable
        run: chmod +x ./.github/scripts/*.sh
      - name: Check version
        working-directory: .
        run: ./.github/scripts/check_version.sh $(echo "${{ github.ref }}" | sed -e "s,^refs/tags/,,")
      - name: Patch Doxyfile
        working-directory: .
        run: ./.github/scripts/patch_doxyfile.sh $(echo "${{ github.ref }}" | sed -e "s,^refs/tags/,,")
      - name: Generate project documentation with Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          working-directory: .github/doxygen/
          doxyfile-path: ./Doxyfile
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install packaging
      - name: Prepare Doxygen doc page
        run: python ./.github/scripts/prepare_documentation.py "${{ github.ref_name }}"
      - name: Deploy Doxygen documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ github.event.repository.name }}
          enable_jekyll: true
