name: Build Jekyll Site on gh-pages Push

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination ./_site

      - name: Commit and Push built site
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Rebuild site on keypop-doc push" || echo "No changes to commit"
          git push origin keypop-doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
