name: Trigger Documentation Update

on:
  workflow_run:
    workflows: ["Publish API documentation (snapshot)"]
    types:
      - completed
  workflow_dispatch:

jobs:
  notify-doc-site:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: jeanpierrefortune/keypop-doc
          event-type: update-submodules
