name: Publish API documentation (release)
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-doc-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract repository information
        id: repo-info
        run: |
          echo "org_name=${GITHUB_REPOSITORY_OWNER}" >> $GITHUB_OUTPUT
          echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Make scripts executable
        run: chmod +x ./.github/scripts/*.sh

      - name: Check version
        working-directory: .
        run: ./.github/scripts/check_version.sh "${{ steps.repo-info.outputs.version }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install packaging

      - name: Patch Doxyfile
        working-directory: .
        run: ./.github/scripts/patch_doxyfile.sh "${{ steps.repo-info.outputs.version }}"

      - name: Generate project documentation with Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          working-directory: .github/doxygen/
          doxyfile-path: ./Doxyfile

      - name: Prepare Doxygen doc page
        working-directory: .
        run: |
          python ./.github/scripts/prepare_documentation.py \
            --github-org "${{ steps.repo-info.outputs.org_name }}" \
            --repo-name "${{ steps.repo-info.outputs.repo_name }}" \
            --version "${{ steps.repo-info.outputs.version }}"

      - name: Deploy Doxygen documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ github.event.repository.name }}
          enable_jekyll: true