name: Publish API documentation (snapshot)

on:
  push:
    branches:
      - main
      - doxygen
  workflow_dispatch:

jobs:
  publish-doc-snapshot:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make scripts executable
        run: chmod +x ./.github/scripts/*.sh
      - name: Patch Doxyfile
        working-directory: .
        run: ./.github/scripts/patch_doxyfile.sh
      - name: Generate project documentation with Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          working-directory: .github/doxygen/
          doxyfile-path: ./Doxyfile
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install packaging
      - name: Prepare Doxygen doc page
        run: python ./.github/scripts/prepare_documentation.py
      - name: Deploy Doxygen documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ github.event.repository.name }}
          enable_jekyll: true
