name: Publish API documentation (release)
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-doc-release:
    name: Generate and publish documentation
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract repository information
        id: repo-info
        shell: bash
        run: |
          {
            echo "org_name=${GITHUB_REPOSITORY_OWNER}"
            echo "repo_name=${GITHUB_REPOSITORY#*/}"
            echo "version=${GITHUB_REF#refs/tags/}"
          } >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install packaging

      - name: Check version
        run: python .github/scripts/check_version.py "${{ steps.repo-info.outputs.version }}"
        if: github.event_name == 'release'

      - name: Patch Doxyfile
        run: python .github/scripts/patch_doxyfile.py "${{ steps.repo-info.outputs.version }}"

      - name: Generate documentation
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          working-directory: .github/doxygen/
          doxyfile-path: ./Doxyfile

      - name: Prepare documentation
        run: |
          python .github/scripts/prepare_documentation.py \
            --github-org "${{ steps.repo-info.outputs.org_name }}" \
            --repo-name "${{ steps.repo-info.outputs.repo_name }}" \
            --version "${{ steps.repo-info.outputs.version }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ github.event.repository.name }}
          enable_jekyll: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'docs: update ${{ steps.repo-info.outputs.version }} documentation'